### ISSUE TITLE
Подробная установка

### ISSUE THREAD

**Issue by bit-trade** [dima-bzz/hd.rustem#1]
Доброго времени суток. 
Возникла проблема при установке. На следующем этапе после подключения к БД. Установка прерывается либо прекращается. Не понятно что происходит. 
![ps01](https://cloud.githubusercontent.com/assets/27817378/25393431/1e917e62-29e4-11e7-9aa7-2e80e59abf29.png)
![ps02](https://cloud.githubusercontent.com/assets/27817378/25393438/22654cbc-29e4-11e7-8a93-c93625c20254.png)
Вопрос. Где можно найти ман с подробным описанием установки системы?

**Comment by dima-bzz** [comment]
Mysql установлен? Логин такой существует в Mysql?

**Comment by bit-trade** [comment]
@dima-bzz конечно, а как иначе.

**Comment by dima-bzz** [comment]
@bit-trade А база соответственно не создается в Mysql? А если попробовать пользователя root. И проверить права на conf.php

**Comment by dima-bzz** [comment]
@bit-trade Можно посмотреть что пишитесь в логах apache /var/log/apache/error.log

**Comment by bit-trade** [comment]
@dima-bzz хорошо, завтра проверю Ваши замечания и отвечу

**Comment by bit-trade** [comment]
Добрый день.
С использованием пользователя root и именем БД hd.rustem ситуация не изменилась. Тот же результат как на скринах.
Права на conf.php:
`-rwxrwxrwx 1 www-data www-data      0 Мар 31 17:29 conf.php`
Apache в логе ошибок ничего не пишет, но в логе доступа к хосту фиксирует внутреннюю ошибку сервера:
`[26/Apr/2017:11:09:26 +0300] "GET / HTTP/1.1" 200 2015`
`[26/Apr/2017:11:09:28 +0300] "GET /index.php?mode=check_install HTTP/1.1" 200 1564`
`[26/Apr/2017:11:09:31 +0300] "GET /index.php?mode=db_install HTTP/1.1" 200 1689`
`[26/Apr/2017:11:09:55 +0300] "POST /index.php HTTP/1.1" 500 2492`
Пытаюсь заставить писать лог ошибок php - пока тоже молчит как лог ошибок apache

**Comment by bit-trade** [comment]
И ещё вопрос. Есть требования к версии php?
На хосте установлена версия:
`PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )`
`Copyright (c) 1997-2017 The PHP Group`
`Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`
`    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies`

**Comment by dima-bzz** [comment]
@bit-trade Версия php 5

**Comment by bit-trade** [comment]
В помощь всем тем у кого возникнет подобная проблема.
Если вы используете ОС Ubuntu 16.04 LTS - не устанавливайте apache, php и mysql командой:
`sudo apt install lamp-server^`
Она вам установит php версии 7, которая не подходит по требованиям системы.

**Comment by bit-trade** [comment]
@dima-bzz действительно проблема была в версии php. На 5-й версии установилось без проблем.
![ps03](https://cloud.githubusercontent.com/assets/27817378/25434777/4f96e5f8-2a96-11e7-877b-7bd940307710.png)

**Comment by dima-bzz** [comment]
@bit-trade Отлично)) Добавлю что нужно использовать php5.
