### ISSUE TITLE
Ошибка при перенаправлении, после авторизации

### ISSUE THREAD

**Issue by rainbowromka** [dima-bzz/hd.rustem#10]
Захожу на страницу по адресу внутри сети servername:9180. У нас на предприятии на сервере на 80 порту сидят другие сервисы.  Этот сервис мы решили посадить на порт 9180 или любой произвольный. После удачной авторизаций (ввода имени пользователя и пароля) происходит перенаправление на страницу. В строчке 78 файла index.php строка 

` if ($rq==1) { header("Location: http://".$url['host'].$req_url);} `

я так палагаю, она неправльно отрабатывает порты в ссылке.
в результате прыгаем в пустоту (страница не найдена или ошибка соединения).
для своего порта я прописал заплатку:

` if ($rq==1) { header("Location: http://".$url['host'].":9180".$req_url);}`

Заплатку залечил у себя. Но решил попробовать написать вот такой код:

`if ($rq==1) { header("Location: http://".$url['host'].(isset($url['port']) ? ":".$url['port'] : "").$req_url);}`

Что скажете вылечите? Может мне тоже взять на поддержку данный проект?

**Comment by dima-bzz** [comment]
@rainbowromka Конечно приму ваше исправление))) Это хорошая идея, так как одному тяжело поддерживать.
