### ISSUE TITLE
Проблемы с загрузкой image файлов

### ISSUE THREAD

**Issue by galandetsv** [dima-bzz/hd.rustem#11]
В настройках расширение файлов стоят phg и jpg. Но файлы этого типа не добавляются не в комментариях, не к заявке. Точнее сам процесс загрузки проходит без ошибок. Заявка/комментарии  добавляются успешно, но потом просто нет этих файлов. Они не загружаются в БД и на сервер. Файлы doc , exel, rar нормально грузятся. 
Обновил JS:
jquery.fileupload-image.js	
jquery.fileupload-jquery-ui.js
jquery.fileupload-process.js
jquery.fileupload-ui.js
jquery.fileupload-validate.js
jquery.fileupload.js
jquery.iframe-transport.js

взял от сюда: https://github.com/blueimp/jQuery-File-Upload/tree/master/js

**Comment by galandetsv** [comment]
Если включить debug_mode то в консоле при любом файле

VM2769:3 Uncaught TypeError: Cannot read property 'length' of undefined
    at eval (eval at b (http://192.168.132.201/helpdesk/js/tmpl.min.js:1:74), <anonymous>:3:690)
    at http://192.168.132.201/helpdesk/js/tmpl.min.js:1:253
    at http://192.168.132.201/helpdesk/js/tmpl.min.js:1:253
    at t.(anonymous function).(anonymous function)._renderTemplate (http://192.168.132.201/helpdesk/js/jquery.fileupload-ui.js:487:26)
    at t.(anonymous function).(anonymous function)._renderTemplate (http://192.168.132.201/helpdesk/js/jquery-ui-1.10.4.custom.min.js:6:5029)
    at t.(anonymous function).(anonymous function)._renderDownload (http://192.168.132.201/helpdesk/js/jquery.fileupload-ui.js:512:25)
    at t.(anonymous function).(anonymous function)._renderDownload (http://192.168.132.201/helpdesk/js/jquery-ui-1.10.4.custom.min.js:6:5029)
    at n.fn.init.<anonymous> (http://192.168.132.201/helpdesk/js/jquery.fileupload-ui.js:234:53)
    at j (http://192.168.132.201/helpdesk/js/jquery-1.11.0.min.js:2:27136)
    at Object.fireWith [as resolveWith] (http://192.168.132.201/helpdesk/js/jquery-1.11.0.min.js:2:27949)

**Comment by galandetsv** [comment]
Так же обнаружил что файлы грузятся в папку \upload_files   но не отображаются. Значит проблема не  jquery

**Comment by dima-bzz** [comment]
@galandetsv Проверьте права на папку. Возможно в этом проблема, так как у меня загружаются!

**Comment by galandetsv** [comment]
любые, "111.png", "ываывавы.png", "sdfsfsdf.png"

**Comment by galandetsv** [comment]
https://yadi.sk/d/BZXTU6yi3QDhA5 скрины

**Comment by dima-bzz** [comment]
@galandetsv А index_comment.php в логах браузера что возвращает?

**Comment by dima-bzz** [comment]
@galandetsv Разобрался. Нужно удалить папку thumbnail. Она при загрузке файла сама создается с правильными правами.

**Comment by galandetsv** [comment]
А где эта папка лежит? поиск не нашел ее

**Comment by galandetsv** [comment]
А может у меня проблема как раз с правами доступа? не создается папка

**Comment by dima-bzz** [comment]
@galandetsv Сделайте на главную папку со всеми вложениями права 777

**Comment by galandetsv** [comment]
https://yadi.sk/i/SKKh9WD63QDpqW дал права, перезапустил апатч проблема осталась .Может ее вручную создать попробовать? куда и какую папку надо?

**Comment by dima-bzz** [comment]
@galandetsv В папке upload_files

**Comment by galandetsv** [comment]
https://yadi.sk/d/8jXTV8GR3QE24c  пересоздал папку от root. Результата не дало.  Может на сервере какой библиотеки не хватает?  php 7 кстати

**Comment by galandetsv** [comment]
А можно отключить превью фото?

**Comment by dima-bzz** [comment]
@galandetsv C php7 не тестировал и вроде как не очень работает. Лучше php5. Ну это нужно смотреть позволяет ли плагин это.

**Comment by galandetsv** [comment]
https://yadi.sk/d/oeqgq3bP3QEDXh сделал владельцем  www-data  папки upload_files  и thumbnail, не получилось. попробовал удалить папку thumbnail. Результат тоже. Апач перезапускал

**Comment by dima-bzz** [comment]
@galandetsv В chrome вывод в инструментах разработчика -> разделе network -> файл index_comment.php

**Comment by galandetsv** [comment]
https://yadi.sk/i/xmKz2OUQ3QEKkH  

{files: [{name2: "nastol.com.ua-100606.jpg", name: "rz1hqbcn7mfuwmpw1ooz8tex.jpg", size: 1657944,…}]}
files
:
[{name2: "nastol.com.ua-100606.jpg", name: "rz1hqbcn7mfuwmpw1ooz8tex.jpg", size: 1657944,…}]
0
:
{name2: "nastol.com.ua-100606.jpg", name: "rz1hqbcn7mfuwmpw1ooz8tex.jpg", size: 1657944,…}
deleteType
:
"DELETE"
deleteUrl
:
"http://192.168.132.201/helpdesk/upload_files/?file=rz1hqbcn7mfuwmpw1ooz8tex.jpg"
error
:
"Failed to resize image (original, thumbnail)"
name
:
"rz1hqbcn7mfuwmpw1ooz8tex.jpg"
name2
:
"nastol.com.ua-100606.jpg"
size
:
1657944
type
:
"image/jpeg"
url
:
"http://192.168.132.201/helpdesk/upload_files/rz1hqbcn7mfuwmpw1ooz8tex.jpg"

**Comment by dima-bzz** [comment]
@galandetsv Файл появляеться в upload_files? И попробуйте поставить php5

**Comment by galandetsv** [comment]
в upload_files появляется, а папка thumbnail не создается (а если вручную создать то файл туда не попадает) и нет записи в БД об этих файлах. 
Щас попробую php 5. Но на PHP 7 все прекрасно работает, кроме вот создание превьюшки.

**Comment by galandetsv** [comment]
щас попробую обновить UploadHandler.php и UploadHandlerComment.php

**Comment by galandetsv** [comment]
нашел UploadHandler.php на https://github.com/blueimp/jQuery-File-Upload/tree/master/server/php заменил. Но загрузка совсем перестала работать. вернул все назад

**Comment by dima-bzz** [comment]
@galandetsv Всетаки поставьте php5 потому что сложно искать решение проблемы если разны версии стоят!

**Comment by dima-bzz** [comment]
@galandetsv [вот тут посмотрите](https://stackoverflow.com/questions/28103078/jquery-file-upload-failed-to-resize-image-original-thumbnail)

**Comment by galandetsv** [comment]
Установил пакет php-imagix и все заработало. Спасибо тебе добрый человек) Очень классная система. Если честно не ожидал что мне тут помогу, думал проект уже давно заброшен.

**Comment by galandetsv** [comment]
Получается что на php 7 все нормально работает.

**Comment by dima-bzz** [comment]
@galandetsv Не за что. Исходный проект разработчики перестали поддерживать. Они перешли на платную версию. Этот fork поддерживаю я, ну и доработал немного.

**Comment by galandetsv** [comment]
Вот я тоже хочу попробовать доработать. Добавить подтверждение выполнение заявки автором, что бы только после этого она считалась выполненной.  Но не знаю хватит ли моих знаний на это.

**Comment by dima-bzz** [comment]
@galandetsv Пробуйте. Если что спрашивайте, чем смогу - помогу.
