### ISSUE TITLE
Добавление возможности редактирование срока заявки

### ISSUE THREAD

**Issue by galandetsv** [dima-bzz/hd.rustem#12]
Добрый день, пытаюсь добавить возможность редактировать дедлайн тикета. 

В файл ticket.php между <form> добавил:

    <div class="control-group" id="deadline_in">
        <div class="controls">
              <div class="form-group">
        <label for="deadline_t" class="col-sm-2 control-label"><small><?=lang('NEW_deadline');?>: </small></label>
        <div class='col-sm-10'>
<div class='input-group date' id='deadline' data-toggle="tooltip" data-placement="right" title="" data-original-title="<?=lang('NEW_deadline_info');?>">
    <input type='text' class="form-control input-sm" id="deadline_t" placeholder="<?=lang('NEW_deadline');?>">
    <span class="input-group-addon" >
        <span class="fa fa-calendar"></span>
    </span>
</div>
</div></div></div></div>

форма появилась но не срабатывает, не как не могу в коде найти JS для работы с datetimepicker

в core.js нашел: 

$('body').on('click', 'button#reset_ticket', function(event) {
        event.preventDefault();
        window.location = MyHOSTNAME+"create";
        });
        $('#deadline').datetimepicker({
            locale: 'ru',
            format: 'YYYY-MM-DD HH:mm',
            sideBySide:true,
            allowInputToggle:false,
            focusOnShow:true,
            useCurrent:false,
            toolbarPlacement: 'bottom',
            showTodayButton: true,
            showClear: true,
            showClose:true,
            tooltips:(function(){})
        });

Но это я как понимаю только для сброса при нажатии на ресет.

**Comment by dima-bzz** [comment]
@galandetsv Есть более удобный способ общения?

**Comment by galandetsv** [comment]
Сбросил в скайп на почту

**Comment by galandetsv** [comment]
Сделал кнопку в редактировать "изменить крайний срок:"  скидываю измененный файлы https://drive.google.com/open?id=1szROc1O9SAGpS7sJt02IcxzQfMP1UbQE   единственное в "история изменений" после смены приоритета или срока заявки прописывается "в заявке было изменено сообщение"  . Пока не нашел как поправить.

**Comment by dima-bzz** [comment]
@galandetsv Для этого нужно в actions.php изменить ':edit_msg'=>'edit_msg' на ':edit_deadline'=>'edit_deadline'. Потом нужно добавить в functions в разделе все уведомлений
get_last_action_ticket
get_last_action_ticket_noty
get_last_action_ticket2
get_last_action_ticket_jabber
get_last_action_ticket_mail
get_last_action_ticket_mail_subj

А так же добавить в настройка профиля и добавления и редактирования пользователя как уведомления рассылать.

Как-то так))

**Comment by galandetsv** [comment]
Спасибо) все получилось.  У меня еще вопрос не по этой теме. Когда я первый раз установил систему под пользователем видел статистику в виде "круга с диограмой", а вот сейчас я не чего подобного не вижу. Меня не приглючило?  так то сейчас у меня для рядового сотрудника нет статистики.

**Comment by dima-bzz** [comment]
@galandetsv На главной странице нужно щелкнуть по "Статистика заявок"

**Comment by galandetsv** [comment]
оо. Точно)  Вот следующее, что хочу доработать. так это выбор периода статистики. К примеру за  месяц, неделю и между датами. Как я понимаю достаточно в functions.inc.php  переделать функции.

**Comment by dima-bzz** [comment]
@galandetsv [Посмотрите тут.](https://adminlte.io/themes/AdminLTE/pages/charts/chartjs.html) Лучше обновить плагин. Будет покрасивее)))

**Comment by galandetsv** [comment]
Вы имеете ввиду прикрутить туда библиотеку ChartJS ?

**Comment by dima-bzz** [comment]
@galandetsv Необязательно. Там несколько плагинов статистики есть.
