### ISSUE TITLE
При нажатии на кнопку создать пользователя ничего не происходит

### ISSUE THREAD

**Issue by alias095** [dima-bzz/hd.rustem#14]
При нажатии на кнопку создать пользователя системы ничего не происходит

**Comment by alias095** [comment]
С этим разобрался поставил php 5.5  реакция появилась но пользователь все равно не создается

**Comment by opiums9** [comment]
У меня аналогичная проблема, что на 5.6, что на 5.3
500-я ошибка

**Comment by galandetsv** [comment]
Тут где то есть ответ на вопрос почему не создается пользователь. https://github.com/ZENLIX/hd.rustem/issues

**Comment by galandetsv** [comment]
Сам находил но сейчас не помню решение

**Comment by opiums9** [comment]
**galandetsv**, интересный вопрос, а как сделать этот проект работоспособным на IIS7? на апаче всё ок идёт, на IIS проблемы

**Comment by galandetsv** [comment]
Я думаю там много зависимостей от компонентов которых нет в windows. Лучше поднять hiper v c ubuntu
