### ISSUE TITLE
Не работает поиск заявок под учетной записью администратора

### ISSUE THREAD

**Issue by dim246** [dima-bzz/hd.rustem#18]
Добрый день! Под учетной записью администратор система не находит заявки по поиску, если зайти под учеткой с правами начальника отдела поиск работает

**Comment by dima-bzz** [comment]
Добрый день. Какие права у администратор?

**Comment by dim246** [comment]
Начальник управления

**Comment by dima-bzz** [comment]
@dim246 Добрый день! Проверил у себя. Поиск работает нормально. Как именно он у вас не работает?

**Comment by dim246** [comment]
ввожу номер заявки, появляется надпись "нет записей". Какие оптимальные версии php mssql apache для этой системы использовать? Иногда в этом бывает проблема.

**Comment by dima-bzz** [comment]
@dim246 PHP 5 ну и соответствующая версия mysql. Apache тут роли не играет.

**Comment by dim246** [comment]
PHP 5.5 и mysql 5.5 сейчас использую

**Comment by dima-bzz** [comment]
@dim246 Можно скриншот с поиском и того что ищете?

**Comment by dim246** [comment]
Если в системе права у пользователя начальник управления или начальник отдела поиск по номеру заявки работает некорректно, если права сотрудник, то поиск работает хорошо, не могу понять в чем тут проблема

**Comment by dima-bzz** [comment]
@dim246 Так сложно сказать. Так как у меня работает корректно.

**Comment by dima-bzz** [comment]
Добрый вечер. Если есть возможность удалённого подключения, то могу посмотрю что не так.

**Comment by dim246** [comment]
Система стоит на внутреннем сервере управления без доступа в инет(( у вас версия php 5.5 или 5.3?

**Comment by dima-bzz** [comment]
Тогда хотя бы скриншоты и есть ли ошибки в логе apache.

**Comment by dim246** [comment]
Дмитрий, приветствую! Не могу понять логику работы поиска заявок. Есть отдел в нем два сотрудника, права у них нач отдела. Поиск заявок я так понял  работает только у тебя кто инициатор заявки, если второй сотрудник заходит в систему этого же отдела, то система не находит заявки других сотрудников этого отдела, помогите разобраться

**Comment by dima-bzz** [comment]
@dim246 Добрый день! Что значит заходит в систему этого отдела? Есть два сотрудника, у обоих права нач отдела. а так же оба добавлены в отдел в котором они нач отедал. Они должны видеть свои заявки и заявки отдела. Соответсвенно они могут искать заявки в рамках своего отдела и не важно кто ее создал. Как то так.

**Comment by dim246** [comment]
Все верно, только вот если сотруднику установить права нач управления то заявки уже не находит по поиску((((((

**Comment by dima-bzz** [comment]
@dim246 Что пишется в логах? Я протестировал все работает! А сами заявки они видят?

**Comment by dim246** [comment]
Сами  заявки  видны! Если есть возможность посмотреть скину на почту ссылку на сайт

**Comment by dim246** [comment]
в логах ничего нет

**Comment by dima-bzz** [comment]
Кидаете. Посмотрю.

**Comment by dim246** [comment]
отправил на почту
