### ISSUE TITLE
Не работает время выполнения заявки

### ISSUE THREAD

**Issue by dim246** [dima-bzz/hd.rustem#19]
Если заявку еще не взять в работу то идет отсчет времени выполнения заявки, если заявку закрыть то счетчик сбрасывается и показывает что время выполнения заявки 0 секунд, строку 

*/1 * * * * /usr/bin/php5 -f C:\OpenServer\domains\hd/sys/4cron_live_ticket.php > C:\OpenServer\domains\hd/4cron.log 2>&1 в крон добавил

**Comment by dima-bzz** [comment]
@dim246 Добрый день! Скорее всего не работает крон. Если крон работает то при обновление страницы где открыта заявка время выполнение не должно сбрасываться!

**Comment by dim246** [comment]
Строка для крона на openserver может как-то иначе должна выглядеть?

**Comment by dima-bzz** [comment]
@dim246 */1 * * * * /usr/bin/php5 -f C:\OpenServer\domains\hd\sys\4cron_live_ticket.php > C:\OpenServer\domains\hd\4cron.log 2>&1

Может так?

**Comment by dima-bzz** [comment]
@dim246 http://phpstudy.ru/zapusk-php-skripta-cron-openserver.html

**Comment by dim246** [comment]
пробовал по ссылке выше, не получается

**Comment by dim246** [comment]
Хотя нет все получилось, спасибо, просто неверно написал имя файла

**Comment by dim246** [comment]
странно перенос в архив работает с этой записью а время выполнения нет сбрасывает на 0

%progdir%\modules\php\%phpdriver%\php-win.exe -c %progdir%\userdata\temp\config\php.ini -q -f %sitedir%\site.ru\sys\4cron_live_ticket.php

**Comment by dim246** [comment]
для openserver строка будет выглядеть так
%progdir%\modules\php\%phpdriver%\php-win.exe -c %progdir%\modules\php\PHP-5.5\php.ini -q -f %sitedir%\hd\sys\4cron_live_ticket.php. Спасибо!
