### ISSUE TITLE
Пункт меню "Пользователи" (clients)

### ISSUE THREAD

**Issue by bit-trade** [dima-bzz/hd.rustem#2]
Перечень пользователей (клиентов) отображается только под системной учеткой:

![ps_2017-04-27_13-14-37](https://cloud.githubusercontent.com/assets/27817378/25479319/125ed9ae-2b4d-11e7-8e7d-9934d04dd57d.png)

Как заставить систему отображать список клиентов для всех учеток с правами админа и редактирования информации о клиенте?

![ps_2017-04-27_13-13-02](https://cloud.githubusercontent.com/assets/27817378/25479362/3e9567d6-2b4d-11e7-8764-c30d08290ee2.png)
![ps_2017-04-27_13-13-22](https://cloud.githubusercontent.com/assets/27817378/25479369/43de60d0-2b4d-11e7-8e40-09a7bc69f785.png)

**Comment by dima-bzz** [comment]
@bit-trade Добавил возможность. Тестируйте!
