### ISSUE TITLE
Блокировка заявки

### ISSUE THREAD

**Issue by dim246** [dima-bzz/hd.rustem#20]
Если заявку взял в работу сотрудник, справа появляется сообщение о том, что В настоящее время с заявкой работает пользователь Иванов Иван Иванович. 
Поэтому Вы не можете работать с заявкой. Нажмите кнопку с заявкой ознакомился, однако кнопка "восстановить" и "выполнена" активны, то есть с заявкой все равно можно работать, возможно ли это исправить, спасибо.

**Comment by dima-bzz** [comment]
@dim246 Добрый день! Нужно больше информации. На кого делается заявка и у кого активны кнопки?

**Comment by dim246** [comment]
Есть отдел в котором 2 сотрудника, один сотрудник этого отдела взял заявку в работу, но у другого сотрудника этого отдела кнопки активны то есть по факту заявка не блокируется

**Comment by dima-bzz** [comment]
@dim246 Какие права у сотрудников?

**Comment by dim246** [comment]
Права у сотрудников начальник отдела, заявка делается на отдел
