### ISSUE TITLE
Архив заявок

### ISSUE THREAD

**Issue by dim246** [dima-bzz/hd.rustem#21]
Добрый день! Подскажите по какому принципу заявки уходят в архив.

**Comment by dima-bzz** [comment]
@dim246 Добрый день. После выполнения заявки и от этого дня через количество дней указанного в настройках. По умолчанию вроде 3 дня.

**Comment by dim246** [comment]
Дмитрий, выражаю благодарность за поддержку данной систем. Какие возможные обновления ожидаются для системы? Как с вами можно взаимодействовать для доработки тех или иных функций по запросу?

**Comment by dima-bzz** [comment]
Добрый вечер. Пока не каких глобальных обновлений не предвидится. Но в планах хочется переехать на adminlte. Но это будет сложно одному сделать. Плюс добавить socket для оповещения ну и тд. По доработке можете обращаться через почту. Если будет время и возможность, то смогу помочь.
