### ISSUE TITLE
Установка.

### ISSUE THREAD

**Issue by SharkyVan** [dima-bzz/hd.rustem#22]
Добрый день.
Установил, установка прошла без ошибок, все хорошо. На главную страницу заходит без проблем, но при попытке зайти в любой раздел, будь то настройки или заявки, выдает ошибку
![image](https://user-images.githubusercontent.com/40848207/42303684-a5e047bc-804c-11e8-9b45-3d3ca95c7172.png)
В чем может быть дело? При этом, если руками набирать server/support/inc/files.php, например, то открывается и работает...
Php 5.4.16, centos 7.

**Comment by dima-bzz** [comment]
Добрый день. А какой адрес указывали при установки?

**Comment by SharkyVan** [comment]
Так она ж не спрашивает адрес? Просто распаковал архив в папку, настроил апач, и зашел на http://172.19.30.12/support/ .

**Comment by dima-bzz** [comment]
При установки где указывается база и пароль. Там есть еще адрес системы. Какой указали?

**Comment by SharkyVan** [comment]
localhost

**Comment by dima-bzz** [comment]
Надо писать адрес тот который вы используете. Тоесть http://server/support

**Comment by SharkyVan** [comment]
![image](https://user-images.githubusercontent.com/40848207/42305546-9ca6596c-8055-11e8-828e-d895688f4862.png)
![image](https://user-images.githubusercontent.com/40848207/42305561-a9360b50-8055-11e8-91e2-1abaacf24f3e.png)

**Comment by dima-bzz** [comment]
Да все верно тут localhost.  Mod_rewrite включен?

**Comment by SharkyVan** [comment]
да, по httpd -M показывает rewrite_module (shared)

**Comment by dima-bzz** [comment]
Что в логах apache?

**Comment by SharkyVan** [comment]
[Thu Jul 05 13:13:16.826178 2018] [:error] [pid 30941] [client 172.19.1.109:13658] script '/usr/share/support/index.php' not found or unable to stat, referer: http://172.19.30.12/support/index.php
[Thu Jul 05 13:13:21.960110 2018] [autoindex:error] [pid 27297] [client 172.19.1.109:13674] AH01276: Cannot serve directory /usr/share/support/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive

**Comment by dima-bzz** [comment]
Настройки apache можно еще посмотреть?

**Comment by SharkyVan** [comment]
[httpd.txt](https://github.com/dima-bzz/hd.rustem/files/2165966/httpd.txt)
[support.txt](https://github.com/dima-bzz/hd.rustem/files/2165967/support.txt)

**Comment by dima-bzz** [comment]
https://www.liquidweb.com/kb/apache-error-no-matching-directoryindex-index-html-found-solved/

**Comment by dima-bzz** [comment]
https://www.e2enetworks.com/help/knowledge-base/how-to-enable-mod_rewrite-on-apache-on-centos/
