### ISSUE TITLE
После установки ничего не работает

### ISSUE THREAD

**Issue by mocart2** [dima-bzz/hd.rustem#29]
После успешной установки предлагает авторизоваться под system/1234 и после этого открывается дашборд, наверху появляется подсказка о просмотре инструкций и создании заявки. При нажатии на любую из ссылок (кнопок) выводится сообщение о том, что страница не найдена:
![image](https://user-images.githubusercontent.com/10042982/46392822-acb01500-c71d-11e8-970c-cfb5f4f3a6bd.png)

**Comment by dima-bzz** [comment]
@mocart2 Добрый день. Nginx по другому настраиваться. Используйте Apache

**Comment by mocart2** [comment]
А можно узнать как настроить в nginx?

ср, 3 окт. 2018 г., 18:00 dima-bzz <notifications@github.com>:

**Comment by mocart2** [comment]
Решено:
В корневом location заменил содержимое на:

location / {
    rewrite ^/([a-zA-Z0-9_-]+)$ /index.php?page=$1;
    rewrite ^/([a-zA-Z0-9_-]+)/$ /index.php?page=$1;

}
