### ISSUE TITLE
Привилегии пользователя

### ISSUE THREAD

**Issue by bit-trade** [dima-bzz/hd.rustem#3]
После исправлений пункта меню "Пользователи" (https://github.com/dima-bzz/hd.rustem/issues/2) в настройка привилегий пользователя системы, заметил недоработку. Когда он (пользователя системы) не является администратором то список в пункте меню "Пользователи" не отображается. Это возможно исправить?

Плюс поправить настройку привилегий так, чтоб права на редактирования списка и добавления нового клиента включались/отключались по выставлению соответствующего флажка? Т.е. флажок на "Добавление клиента" - кнопка над списком, флажок на "Редактирование клиента " - ФИО как ссылка на редактирование данных клиента.

**Comment by dima-bzz** [comment]
@bit-trade Не совсем понял. Можно скриншоты.

**Comment by bit-trade** [comment]
@dima-bzz хорошо, немного позже

**Comment by bit-trade** [comment]
Вот смотрите. По первой части вопроса.
Входим под пользователем системы без прав администрирования, но с привилегиями добавления и редактирования клиентов. И пытаемся изменить информацию о каком либо клиенте или добавить нового в пункте меню "Пользователи". А там пусто.

![ps_tolik](https://cloud.githubusercontent.com/assets/27817378/25526845/4043fac6-2c1e-11e7-926a-29d3084be9e7.png)
![ps_2017-04-28_11-48-36](https://cloud.githubusercontent.com/assets/27817378/25526868/5527e8f8-2c1e-11e7-84d0-22984e64ea26.png)

По второй части. На скрине показано, что чекбоксы привилегий не работают в пункте меню "Пользователи". Потому, что по логике список должен отображаться но без кнопки "Добавить" и активных ссылок ФИО

![ps_miron](https://cloud.githubusercontent.com/assets/27817378/25527122/e2ede5a6-2c1f-11e7-918f-f0b4b6b8d11d.png)
![ps_2017-04-28_11-50-48](https://cloud.githubusercontent.com/assets/27817378/25527125/e63ed0a8-2c1f-11e7-9982-92ae9d8d24b8.png)

**Comment by dima-bzz** [comment]
@bit-trade Добавление пользователей доступно только для Администраторов. Добавление и редактирование относиться к созданию заявки. Там есть карточка клиента в которой можно отредактировать клиента или создать его если нет. Но это только для клиентов. Эти пункты я не использую. Суть в том что систему можно использовать без участия в ней (без регистрации).

**Comment by dima-bzz** [comment]
@bit-trade Пользователи должны отображаться только администраторам!

**Comment by dima-bzz** [comment]
@bit-trade Это таблица клиентов и она не должна отображаться. Она работает только по поиску! Это два разных пункта системы.

**Comment by bit-trade** [comment]
@dima-bzz 
> Пользователи должны отображаться только администраторам!

Очень жаль, можно было использовать в качестве телефонного справочника

> Суть в том что систему можно использовать без участия в ней (без регистрации).

Как это возможно? Получается нам не обязательно регистрировать пользователей в системе, чтоб они могли делать заявки?

**Comment by dima-bzz** [comment]
@bit-trade Можно создать заявку от Имени конкретного клиента. Например Ген. директор не будет сидеть в системе, но будет раздавать задания. Вот как раз от его имени можно создать заявку. Для этого как раз и нужны Клиенты.

**Comment by bit-trade** [comment]
@dima-bzz а Вы об этом, теперь ясно.
Спасибо за разъяснение.

**Comment by dima-bzz** [comment]
@bit-trade Посмотрите в сторону [https://github.com/dima-bzz/Accounting-technology] Там как раз это реализовано.

**Comment by dima-bzz** [comment]
@bit-trade Вообще лучше не делать администраторами пользователей с привилегиями сотрудник и начальник отдела. Лучше сделать администратором Начальника управления!
