### ISSUE TITLE
Невозможно подтвердить регистрацию

### ISSUE THREAD

**Issue by pautiina** [dima-bzz/hd.rustem#37]
![image](https://user-images.githubusercontent.com/11805503/51740784-b3341500-209d-11e9-8c69-ee9bc243888c.png)
Пытаюсь подтвердить регистрацию на сайте https://ddteam.tech/, но выдает ошибку.

**Comment by dima-bzz** [comment]
@pautiina Пробуйте подтвердить регистрацию сейчас

**Comment by pautiina** [comment]
Успешно
