### ISSUE TITLE
Невозможно произвести установку

### ISSUE THREAD

**Issue by pautiina** [dima-bzz/hd.rustem#38]
Сегодня попробовал произвести установку vmdesk, но на последнем шаге выходит пустое окно.
![image](https://user-images.githubusercontent.com/11805503/51741077-82a0ab00-209e-11e9-954a-80b6900e5b5c.png)

Посмотрел код файла `sys/install.php` там используется библиотека `mysql`, и в некоторых файлах тоже используется устаревшая библиотека, а в большинстве используется PDO.
Связи с тем, что у меня установлен php  7.1.x - произвести установку без компиляции версии php 5.6 - **невозможно**!

**Comment by dima-bzz** [comment]
@pautiina  Версия php 7.1 пока не поддерживается системой

**Comment by pautiina** [comment]
Будем ждать

**Comment by pautiina** [comment]
Исправлено в вресии 2.0.0 с оф. сайта.
