### ISSUE TITLE
Проблема с выводом тикетов для пользователя с правами "сотрудник".

### ISSUE THREAD

**Issue by zetcamp** [dima-bzz/hd.rustem#4]
Версия "заявок" самая крайняя.
Версия системы Ubuntu 16.04 + xampp 5.6.30.
Браузеры Firefox 53 + Chrome.

Добрый день!

Если у _пользователя системы_ права "**сотрудник**", то при переходе в "**Список заявок**" вечно крутится "кольцо загрузки", и заявки не выводятся.

На начальной странице заявки _пользователю системы_ видны в разделе "**Последние изменения**" и "**Последние входящие заявки**", можно их открывать. Но это не удобно, если заявок много.

Если _пользователю системы_ поставить права "**Начальник отдела**" или "**Начальник управления**" - то "**Список заявок**" открывается нормально, но это исключает изоляцию _пользователя системы_ от просмотра заявок, адресованных не ему.

Спасибо за любой ответ.

П.С.
В оригинальной версии с rustem-art/hd.rustem такой проблемы нет, но Ваш форк более удобен и функционален. 

![clipboard01](https://cloud.githubusercontent.com/assets/10241034/26142415/11de4676-3ae9-11e7-9608-97b47212c42e.jpg)

**Comment by dima-bzz** [comment]
@zetcamp Исправил ошибку. Проверяйте :)

**Comment by zetcamp** [comment]
Проверил. ;) Результат немного изменился, теперь при входе _пользователя системы_ с правами "**сотрудник**" просто пустое окно. Ни шапки, ничего нет. 

Что сделал:
1. Закинул поверх всё из архива с перезаписью файлов кроме файла конфигурации. Не помогло.
2. Снёс базу, снёс файл конфигурации, прошёл процедуру установки, всё отлично и красиво. Создал свеженького пользователя системы_ с правами "**сотрудник**" и ему задачу повесил. Зашёл под сотрудником - пустой экран.

Если изменить сотруднику права на +1 или +2 - то стартовая страница (и любые другие) при входе отображается корректно.

**Comment by dima-bzz** [comment]
@zetcamp Скачал архив и перезаписал. Удалил базу, создал новую. Проверил все работает.

**Comment by dima-bzz** [comment]
@zetcamp MySql стоит или  что-то другое?

**Comment by zetcamp** [comment]
Так, сейчас попробую провернуть тот же трюк. Удалю базу, создам новую. Стоит xampp 5.6.30 - в нём:
Сервер баз данных
    Сервер: Localhost via UNIX socket
    Тип сервера: MariaDB
    Версия сервера: 10.1.21-MariaDB - Source distribution
    Версия протокола: 10
    Кодировка сервера: UTF-8 Unicode (utf8)

Веб-сервер
    Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3
    Версия клиента базы данных: libmysql - mysqlnd 5.0.11-dev - 20120503
    Версия PHP: 5.6.30

**Comment by dima-bzz** [comment]
@zetcamp Не могу сказать что на MariaDB работает

**Comment by zetcamp** [comment]
Хорошо, это всё равно результат, сейчас поищу Мускуль, накачу и отпишусь,чтоб закрыть тикет и точно указать, что с xammp не работает.
