### ISSUE TITLE
Не проблема - вопрос по расширению функционала.

### ISSUE THREAD

**Issue by zetcamp** [dima-bzz/hd.rustem#5]
Добрый день!

Суть вопроса - имеется ли возможность добавить выпадающий список с "Пользователями системы" и "Отделами системы" (или два разных списка рядом) в качестве фильтра при выводе заявок в окне "Список заявок"?

Конкретно, что-то типа такого:
![-2](https://cloud.githubusercontent.com/assets/10241034/26250728/abdfba4a-3cb3-11e7-9ad6-3247886f7a54.jpg)

Т.е. добавить фильтр, с помощью которого можно отобразить только завяки, исполнителем которых является выбранный "пользователь" или "отдел". При выборе из одного выпадающего списка, в другом выбранный элемент сбрасывается.

Спасибо за любой ответ!

**Comment by dima-bzz** [comment]
@zetcamp Для этого есть раздел Общая статистика.

**Comment by dima-bzz** [comment]
@zetcamp Добавил возможность просмотра общей статистики для Админов и Нач.управеления

**Comment by zetcamp** [comment]
Спасибо, извиняюсь, сегодня до сего момента не было возможности добраться до интернета. Я обязательно отпишусь, если ещё что-то найду.
