### ISSUE TITLE
Шаблон заявки

### ISSUE THREAD

**Issue by gav80** [dima-bzz/hd.rustem#6]
Добрый день.
Скажите, не планируется ли такой функционал как шаблоны при создании новой заявки.
Если пользователь, например, в поле Кому (Исполнитель) выбирает такой-то пункт (Отдел1), то в теле заявки появляются какие-то доп. пункты (списки, чекбоксы, и т.п.). А если выбирает в поле Кому другой пункт (Отдел2), то подгружается другой шаблон, т.е. в теле заявки появляются иные доп. поля.

**Comment by dima-bzz** [comment]
@gav80 По подробнее расскажите ваше предложение.

**Comment by gav80** [comment]
Начинаем создавать новую заявку. Пока все выглядит стандартно...

1) В Теме, например, выбираем пункт "Заправка картриджа"
2) Появляется (где-нибудь после Темы) дополнительный выпадающий список (select) с моделями принтеров (вот так схематично - http://prntscr.com/fpngn1)

Другой вариант
1) В Теме выбираем пункт "Сетевые ресурсы"
2) Появляется список ресурсов (имена каталогов). При выборе каждого каталога можно отмечать (например, галочками) права доступа.

Еще вариант
1) В Теме выбираем 1С
2) Появляется список с именами баз
3) Выбираем какую-то базу
4) Появляются еще какое-то уточняющие параметры уже к выбранной базе

-----
Т.к. вариации разные (вот я навскидку три написал выше), то удобней это сделать с помощью доп.полей.
Т.е., например, в настройках указываем, что при выборе Темы "Заправка картриджей" вставляется доп.поле "выпадающий список" вот с такими пунктами.
При выборе пункта в выпадающем списке (такая-то база 1С) появляется список из чекбоксов, а при выборе другого пункта (базы 1С) появляется другое доп.поле, к примеру, какой-то еще один выпадающий список.

----
Но это я описал сложную систему. Можно сделать простую. Т.е., при выбое Темы "1С" появляется доп.поле "выпадающий список" с именами баз. И все, на этом закончили, нет никакого второго доп.поля после выбора определенной базы.

----
Понятно, что работа большая, поэтому я не прошу сделать так, а интересуюсь, планируется ли это.

**Comment by dima-bzz** [comment]
@gav80 Выпустил обновления с вашей просьбой. Тестируйте :)

**Comment by gav80** [comment]
Спасибо :) Дойдут руки, обязательно подробно посмотрю.
Пока навскидку тройка косячков:
1) В файле BD\HD.db.sql в строке `/*!40000 ALTER TABLE `dop_field` ENABLE KEYS */;` ошибка, нужно `dop_field` заменить на `dop_fields`
2) Самом конце файла js\core.js , как я понял, лишние скобки `});`
3) Когда их убираешь, выскакивает ошибка `core.js:4362 Uncaught ReferenceError: ispath is not defined`

Дальше пока не смотрел.

**Comment by dima-bzz** [comment]
@gav80 Поправил))

**Comment by gav80** [comment]
Да. Теперь работает.
Правда, вскрылась еще одна неприятность (или же это только у меня так?):
Не уверен, что правильно понял причину. Сразу не обратил внимания. Такое чувство, что, когда первый открываешь в админке Общие настройки системы (где заголовок, url и т.п.), там вместо значений стоят placeholder'ы, и если нажать кнопку Редактировать, то значения слетают, и в БД пишется - undefined. Приходится напрямую править БД, тогда все возвращается. И после этого можно снова редактировать, ничего не портится.

**Comment by dima-bzz** [comment]
@gav80 Можно поподробнее. Не совсем понял что и когда слетает.

**Comment by gav80** [comment]
Да, так и не смог воспроизвести описанный глюк, так что, скорее всего, или случайный сбой у меня был, или что-то еще. Ложная тревога.
------

Проверил работу доп.полей. Работают. Но поле мультиселект не отображается, пустое место - http://prntscr.com/fs7c0v

**Comment by gav80** [comment]
Да, так и не смог воспроизвести описанный глюк, так что, скорее всего, или случайный сбой у меня был, или что-то еще. Ложная тревога.

-------
Проверил работу доп.полей. Работают. Но поле мультиселект не отображается, пустое место - http://prntscr.com/fs7c0v

**Comment by dima-bzz** [comment]
@gav80 Исправил. Тему не обязательно указывать в доп полях. Если тема не указана, то доп поля буду отображаться перед кнопкой отправить.
