### ISSUE TITLE
Выбор событий-триггеров для оповещения на почту

### ISSUE THREAD

**Issue by zetcamp** [dima-bzz/hd.rustem#7]
Доброго дня!

Спасибо за кучу обнов, переезд на новую базу был немного тяжеловат, но функционал того стоил. 

Поясняю суть вопроса: возможно ли добавить в настройках пользователя такое же поле выбора типов уведомлений на почту, как для jabber'a? Поскольку сейчас работает только уведомление на почту пользователя о новой заявке, а о всех изменениях в ней (изменение статуса, комментарии) уже молчок.

И да, понимаю, что припозднился с донатом, но всё будет, чес-слово!

П.С.

Прошу помощи/совета - есть кто с успешным вариантом интеграции оповещения через jabber? Может подскажете чего? Стоит OpenFire 4.1.4 - пользователи настроены, ростер общий, на компах меж собой общение есть, для "заявок" тоже пользователь есть, логин/пароль - всё проверено, работает (с любого клиента на ПК), но если завести в систему оповещение через jabber, то результатов ноль. Не уведомляет никак. Кудасмотреть/копать? Логи какие-нибудь.

**Comment by dima-bzz** [comment]
@zetcamp Сделал выбор уведомлений для почты. По поводу Jabber: какое имя сервера используется?

**Comment by zetcamp** [comment]
Спасибо, обновлю, отпишусь. По jabber'у - использую IP-адрес, то бишь, например, 192.168.1.1. Честно говоря, не пробовал указывать имя хоста.

**Comment by dima-bzz** [comment]
@zetcamp У меня по ip тоже не работает. По имени, как указанно на сервере работает)))

**Comment by zetcamp** [comment]
Вот, хорошо, я как проверю с именем - отпишусь дополнительно. Спасибо!

**Comment by zetcamp** [comment]
Теперь совсем хорошо стало - на почту приходит любое выбранной изменения заявки. С jabber'ом так и не победил. Ну и ладно, это отдельная песня. Закрываю тикет. Спасибо!

**Comment by dima-bzz** [comment]
@zetcamp Скиньте на почту свои настройки jabber.
