### ISSUE TITLE
[РЕНЕНИЕ]Проблема с созданием заявки и добавлением пользователей в систему.

### ISSUE THREAD

**Issue by JleHuH213** [dima-bzz/hd.rustem#8]
Заинтересовал проект. Поставил. Столкнулся с проблемой добавления заявок и пользователей. Проблема с заявками решилась при установки значения по умолчанию в бд в таблице tickets у поля ok_date. 
Проблема с добавлением пользователей решилась аналогично. в бд таблицы users у поля last_time. Установил значение по умолчанию и всё отлично работает. Авторам спасибо большое! То что нужно.

**Comment by dima-bzz** [comment]
@JleHuH213 Проверил на чистой базе. Все работает без ваших исправлений! Опишите проблему подробнее.

**Comment by JleHuH213** [comment]
У меня нет проблем =) Я со всеми проблемами разобрался и отписался как я их решил.

**Comment by dima-bzz** [comment]
@JleHuH213 Просто без ваших решений тоже работает. Вот я и пытаюсь выяснить в чем ошибка.

**Comment by JleHuH213** [comment]
У меня получалось так что при запросе в бд в строке              
 ```
  $stmt = $dbConnection->prepare('insert into clients
	     (id, fio, tel, login, unit_desc, adr, email, posada) VALUES
	     (:max_id, :client_fio, :client_tel, :client_login, :unit_desc, :client_adr,  :client_mail, :client_posada)');
```
Выпадало ошибка что last_time не может быть пустым. При добавлении заявок аналогично.

**Comment by dima-bzz** [comment]
@JleHuH213 Строка SQL в файле такого типа **`last_time` datetime NOT NULL**?

**Comment by JleHuH213** [comment]
Да всё верно. Это я понял. Дело всё в том что в запросе мы не указываем этот параметр. Соответственно он подставляет null. Так как не указано значение по умолчанию.

**Comment by dima-bzz** [comment]
@JleHuH213  Когда именно это происходит. Пытаюсь у себя реализовать эту ошибку. Но пока все ок.

**Comment by JleHuH213** [comment]
Да, версия подледная. Ошибка возникает при добавление нового пользователя и при добавлении заявки. Я думаю что ошибка больше связана из за версии или настроек mysql. У Вас при добавлении пользователя значение в поле `last_time ` какое подставляется?

**Comment by dima-bzz** [comment]
@JleHuH213 База сама подставляет 0000-00-00 00:00:00. Жестко при этом не указано.

**Comment by JleHuH213** [comment]
Ну вот. У меня же при установки значения в ручном режиме ругается.

**Comment by dima-bzz** [comment]
@JleHuH213 Вот скрин настроек
![mysql_users](https://user-images.githubusercontent.com/8027583/28710133-93db2934-738b-11e7-8bf7-e12798166fdb.png)

**Comment by dima-bzz** [comment]
@JleHuH213 Версия Mysql какая?

**Comment by JleHuH213** [comment]
Настройки поля `last_time` такие же. Версия mysql: 5.5. Результат запроса: 
`STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

**Comment by dima-bzz** [comment]
@JleHuH213 http://avz.org.ua/wp/2014/04/29/mysql-troubles-after-upgrade-to-5-6/

Вот решение.

**Comment by dima-bzz** [comment]
@JleHuH213 Помогло?

**Comment by JleHuH213** [comment]
Спасибо большое!
